language: python
python:
- '2.7'
install:
- pip install -U platformio
script:
- platformio run
before-deploy:
- |
  (
    mkdir ~/deploy
    cd .pioenvs
    for d in *; do
      if test -f $d/firmware.bin; then
        cp $d/firmware.bin ~/deploy/firmware.$d.bin
      fi
    done
  )
deploy:
  provider: releases
  api_key:
    secure: AZT0YwRVhoJtHnh1ygfGMtX7VCeswOt5FBo5f7+tAaycTVbMKe0WUOOwASf5LuS5TSiqehFxtydGsUheD7dIXQ5xpeUPRePqp+XclOasv4p/+4q/ADKp//X2v3H3FkoFddjOuUPf19Cu2gomjjplaC+F89A339z+w2iz9WtFnBCxA/703Zu/LuvYYkPe0/qxN6T7aPZLExhRiDpkJ+muO6ZTIDjDlWnods9kiRyVN9P92hmAoc+B+yruq8vbFkqMyxHTURLAXP1QQrQrcd6VnaMzjAGvCFqB9Bwdh3Lm88RjGvWsI3VptbBRrmzbrgPpcSEhX3fSIh5oOHH/WKQWiiG9XLKqqPSZLfYSljptQg5ckaTc/HR58OiiXve1w2OtVCRbn8m3OWFPI0O5ZjtBfcj9Z0oHuwYkPnH4VPaN2sgnkpP2S2a4l5AuUTyKFBZiOYIB55hD2R3TQ4m4ZvPFgP0gQWS7TeW9z1PS1ubvpqHrha3upG2n04z7+IhB8w1jMMdmozPWr876eajNgrExvfg4z3MEefF1BeJYZCmeGVg6U2SmfXF7TigHGC12vIluJTvealJwHjh7TkOchJ8gool4EZjA1ol1+SqUCudSTXHhW/muyiH1mC85qenhRy4UH+aNItAm43sqwW9RtLItIh2nn9X67+7eZKWfqrIwcGI=
  file: "~/deploy/*"
  skip_cleanup: true
  on:
    repo: cwi-dis/iotsaGPIO
    tags: true
    all_branches: true
